### PR TITLE
Allow users to save webhooks against their accounts

### PR DESCRIPTION
**Pull request by benjefferies**
Allow users to add webhooks for other notifications other than email

Testing
1. Run app with `pipenv install && pipenv run python run.py`
1. Create user
1. Login
1. Click new account icon
1. Save a webhook
1. Check it's saved

### CODE REVIEW

**Comment by benjefferies** [comment]
@Ali1 let me know what you think

**Comment by Ali1** [comment]
This looks fantastic thank you!!!!

**Comment by Ali1** [comment]
@benjefferies For people like me that create a subscription for a webhook, the email notification is a wasted. Is the best way around this a checkbox saying "Create email notifications?" which if unchecked, would not insert the email address in the subscription table. If unchecked, would also need validation to make sure a webhook has been defined otherwise it would be a subscription without neither a webhook nor an email notifier.

**Comment by benjefferies** [comment]
@Ali1 that sounds like a sensible solution. I think the changes that would need to be implemented are something like:
1. Add a column to the user for notification preferences, this could just be a string (email, webhook, all)
2. When the user adds a subscription check the notification preference and then use this preference when creating the subscription.
3. On changing the notification preference update all subscriptions.

This shouldn't be too hard. Will try and find some time to do this

**Comment by Ali1** [comment]
Tbh I think the notification preference and webhook URL setting should be a setting for each subscription, not a user preference at all.

**Comment by benjefferies** [comment]
Yeah you might be right. The reason I was thinking at user preference initially was that I guess users will either want all subscription notifications via email or webhook not a mix of both.

But then it might just be easy enough to have a checkbox or something on each subscription to toggle notification preferences

**Comment by Ali1** [comment]
You're not wrong about that, most users will have the same notification and URL settings for all their subscriptions. So actually from a user's POV, your way is easier. My way just "seems" more right lol.

**Pull request merged**
